### ISSUE TITLE
errors running this on boot2docker 

### ISSUE THREAD

**Issue by TroyWorks** [jpetazzo/syslogdocker#5]
rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
rsyslogd: activation of module imklog failed [try http://www.rsyslog.com/e/2145 ]
rsyslogd: Could no open output pipe '/dev/xconsole': No such file or directory [try http://www.rsyslog.com/e/2039 ]

**Comment by jpetazzo** [comment]
Those are just warnings that can safely be ignored, since the container has no access to the kernel log or to the graphics console.

**Comment by TroyWorks** [comment]
hmm but with those errors the container doesn't start :(

**Comment by TroyWorks** [comment]
@jpetazzo any ideas?

**Comment by jpetazzo** [comment]
Sorry, reopening

**Comment by jpetazzo** [comment]
I will try to reproduce on the latest Docker Toolbox images.

**Comment by caike** [comment]
Not sure but maybe this can help fix the issue #7 
Thanks for your blog post!

**Comment by jpetazzo** [comment]
Closing old issues; feel free to reopen a new one if you have a similar problem (keep in mind that I'm unfortunately not very actively monitoring issues due to other priorities!)
